### PR TITLE
aws: build after upstream breaking change

### LINKED ISSUE #2890: The build seems to be broken.
I'm working on a mac (OSX 10.10.5) with go via homebrew (version go1.5.1 darwin/amd64).

This is my first attempt to build packer and/but I can't get packer to build correctly.  On the branches tab of the Githubpage, the "default" branch is marked with a red X, clicking through leads to a similar failure to what I'm seeing.  

I ran `make updatedeps` with no errors, but `make` reports:

```
georgewh-L0DKQ1:packer georgewh$ make
go get -v -d ./...
go test ./...  -timeout=15s | tee packer-test.log
# github.com/mitchellh/packer/builder/amazon/common
builder/amazon/common/artifact.go:75: cannot use regionConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_ami_region_copy.go:90: cannot use awsConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_create_tags.go:39: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_modify_ami_attributes.go:93: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
# github.com/mitchellh/packer/builder/amazon/common
builder/amazon/common/artifact.go:75: cannot use regionConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_ami_region_copy.go:90: cannot use awsConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_create_tags.go:39: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_modify_ami_attributes.go:93: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
FAIL	github.com/mitchellh/packer [build failed]
FAIL	github.com/mitchellh/packer/builder/amazon/chroot [build failed]
FAIL	github.com/mitchellh/packer/builder/amazon/common [build failed]
[...]
1 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/mitchellh/packer/builder/amazon/common
builder/amazon/common/artifact.go:75: cannot use regionConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_ami_region_copy.go:90: cannot use awsConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_create_tags.go:39: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_modify_ami_attributes.go:93: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)

==> Copying binaries for this platform...
find: ./pkg/darwin_amd64: No such file or directory

==> Results:
```

### PR DESCRIPTION
**Pull request by rubbish**
see https://github.com/aws/aws-sdk-go/commit/1a69d069352edadd48f12b0f2c5f375de4a636d7

fixes #2890

### CODE REVIEW

**Comment by cbednarski** [comment]
LGTM, thanks!
