### PR TITLE
add ansible provisioner

### LINKED ISSUE #1555: Provide host based Ansible provisioner
The current Ansible provisioner runs Ansible inside the created box, which is totally absurd.

Among other things, it means you can't copy local files to the box using Ansible, which is pretty much the main purpose of provisioning.

Please provide a proper provisioner that runs ansible on the host machine and tells it to connect to the created box via ssh.

### LINKED ISSUE #2732: ansible-local: execute remote
I'm a first-time user of packer and its ansible-local plugin. If I understand correctly, packer takes the entire `roles` directory and moves it to the remote location and calls Ansible there.

This, unfortunately, is a problem for me since my `roles` directory contains a bunch of large files and also some keys which I don't want to see anywhere else but my machine. Luckily, Ansible is made for that purpose (namely to call it locally and move/do stuff on a remote machine). Is there a way to use Ansible in that way through packer?

### PR DESCRIPTION
**Pull request by bhcleek**
Add an Ansible provisioner that does not require installing Ansible on the machine being provisioned.

The `ansible` provisioner uses golang.org/x/crypto/ssh to listen for SSH connections on the Packer host. Ansible uses SFTP to transfer files by default; the `ansible` provisioner executes `sftp-server` on the machine and connects its and Ansible's `stdin`, `stdout`, and `stderr`.

Closes #1555 
Closes #2732

### CODE REVIEW

**Comment by zimbatm** [comment]
I'm surprised nobody from hashicorp has looked at that PR yet. A lot of work seems to have been put into this, going as far as to create a local SSH server to support ansible's connection method.

Anyways, I tested the branch and had to fix a couple of things for it to compile. Fix pushed here: https://github.com/zimbatm/packer/commit/395c707427c0e591e0ecc9632932933a7c034273

Then I got stuck with ansible not being able to connect during facts gathering when using the paramiko adapter: `fatal: [default] => {'msg': "FAILED: (19, 'Operation not supported by device')", 'failed': True}`. When using the openssh adapter it would just hang indefinitely instead.

**Comment by oleyka** [comment]
Please-please-please incorporate this feature in Packer! 

Having to install gcc on a remote box just to be able to run ansible-local there is a totally broken approach...

**Comment by bhcleek** [comment]
@zimbatm I'm happy to help you resolve any issues; I'll take a look at your fixes and incorporate them into this PR in the next couple of days. Thank you for your contribution!

**Comment by bhcleek** [comment]
@zimbatm I incorporated the changes that you identified. Thanks for your help!

**Comment by zimbatm** [comment]
Looks good. I've gone the ansible-local route so won't be following this issue anymore. Best luck for getting it integrated.

**Comment by haad** [comment]
+1

**Comment by peterloron** [comment]
REALLY looking forward to this! Not having to muck around with ansible on my remote machines woudl be awesome!

**Comment by alexanderdean** [comment]
Is this ever going to be merged?

**Comment by cbednarski** [comment]
@alexanderdean I tagged this +1 since there's a lot of community interest. I need to set aside some time to be able to review, merge, and support this; so this is pending having time available.

While you're waiting for this to be merged you can still build and use this plugin with an official packer release, or compile packer from this branch.

**Comment by alexanderdean** [comment]
Thanks so much @cbednarski, much appreciated!

**Comment by bhcleek** [comment]
If you need me to answer any questions or making any changes, @cbednarski, I'm happy to help however I can.

**Comment by akatank** [comment]
Could someone share how to build and use this before it's integrated?

**Comment by bhcleek** [comment]
@jk563 Do you need more information than is contained in the instructions for building packer and the docs added in this PR (https://github.com/mitchellh/packer/pull/1969/files#diff-41abe5770d60431a2efd88808d2a2de3) for using this provisioner?

**Comment by jk563** [comment]
@bhcleek I had a quick attempt before work this morning, failed on updatedeps with an error that mentioned PYTHONPATH and not finding what it needed. Not used Go before so probably doing something silly. Only had 10mins to give it a try so I'll have another look at it later todayand see if I can get it working.

Very much looking forward to using this, thanks for all the effort!

**Comment by jk563** [comment]
Got it built, will try it out tomorrow.

**Comment by LinusU** [comment]
@bhcleek Would it be possible to remove the `SSHAuthorizedKeyFile` and `SSHHostKeyFile` and generate that on the fly? It seems very hacky to either have keys checked in into git, or to have a script checked in which generate the keys.

I think that the nicest would be to just remove the options altogether.

Great work! Hoping that this will get merged. I tried myself the other route, to extract the ssh config from the communicator and use that, but it didn't go so well...

**Comment by bhcleek** [comment]
I'm open to making those changes, and would be willing to do it before its merged if the packer maintainers agree it should be done before integration. Otherwise, I'd like to hold off to avoid delaying integration.

Generating them on the fly isn't too difficult, but I'm not sure how to make sure they'll be used by Paramiko. Any guidance you can provide there would be much appreciated.

It should be said, too, that the files referenced by `SSHAuthorizedKeyFile` and `SSHHostKeyFile` don't need to be committed or generated.

**Comment by jk563** [comment]
Could you explain a bit more about the ssh_host_key_file, ssh_authorized_key_file, and the private-key please? I'm not sure what I should using for these parameters. Also, is the base image expected to have certain users/keys?

**Comment by bhcleek** [comment]
The base image does not need to have any users or keys installed on it other than what you'd already use for packer. This provisioner adapts the SSH model that Ansible uses to the communication model that Packer uses.

I tried to provide useful documentation and an example in https://github.com/bhcleek/packer/blob/ansible-provisioner/website/source/docs/provisioners/ansible.html.markdown.

The `ssh_host_key_file should be a file that contains a valid SSH private key. It will be used as the SSH server's private key.

The `ssh_authorized_key_file` should be a file in the SSH authorized_keys file format. It will be used to verify the key with which Ansible connects to the SSH server that this provisioner provides. In other words, it should be the same kind of file and with the same kind of contents as you'd put on any Ansible node.

**Comment by jk563** [comment]
Using the below configuration I just cannot get this working. Couple of ideas:

Not used paramiko before?
Maybe I'm using keys wrong?
Using a base Fedora 21 image from a fresh install.

Error I get:
==> machine_name: SSH proxy: accepted connection
==> machine_name: failed to handshake

  "provisioners": [
    {
      "type": "ansible",
      "playbook_file": "./playbook.yml",
      "extra_arguments": ["--private-key", "/Users/jamiekelly/.ssh/ansible", "-v", "-c", "paramiko"],
      "ssh_authorized_key_file": "/Users/jamiekelly/.ssh/ansible.pub",
      "ssh_host_key_file": "/Users/jamiekelly/.ssh/ansible_host"
    }
  ]

Any idea what I might be doing wrong?

**Comment by bhcleek** [comment]
@jk563 That looks like Packer is unable to establish a connection to the machine being provisioned. Are you able to get the shell or file provisioners working?

**Comment by jk563** [comment]
@bhcleek  The ever magnificent 
    {
      "type": "shell",
      "inline": ["echo foo"]
    }

works as expected.

The keys are all paths on the host, correct?
Am I also correct in assuming the --private-key and ssh_authorised_key_file should be the two parts of an ssh key pair? And that the host key file is just another random private key?

**Comment by bhcleek** [comment]
You are correct, the `--private-key` and the `ssh_authorized_key_file` should be the two parts of an SSH key pair. Note, though, that the `ssh_authorized_key_file` should be in the authorized keys format (https://en.wikibooks.org/wiki/OpenSSH/Client_Configuration_Files#.7E.2F.ssh.2Fauthorized_keys). The error you are seeing is coming from this provisioner, and simply means that it can't establish a connection. Can you verify that the public `ssh_authorized_key_file` is in SSH Public Key format and, therefore, is not PEM-encoded?

This seems like it's more of a support than a code issue; do you mind if I e-mail you directly?

**Comment by jk563** [comment]
I'll check that out.

Yeah, makes sense to email at this stage.

**Comment by bhcleek** [comment]
@jk563 I've duplicated the behavior you're seeing. The host key must be trusted by your system. You may either include it in your `known_hosts` file, or else use one of the techniques described in the Ansible documentation to [disable host key checking](http://docs.ansible.com/ansible/intro_getting_started.html#host-key-checking).

Using `ssh` for the Ansible connection instead of `paramiko` is sometimes informative, because the Ansible logs are sometimes more detailed when using an `ssh` connection.

One thing that any early adopters (and reviewers!) may want to keep in mind: using SFTP with Ansible will require that the SSH connection to the machine being provisioned be established without a pty. The default behavior for the SSH communicator was changed in #1968 to not request a pty.

**Comment by jk563** [comment]
Got this all working now, will give it more of a test drive soon. Many thanks to @bhcleek for some assistance.

**Comment by hartzell** [comment]
I'm very excited to be able to run Ansible on my provisioning host, not the remote machine.

But, I can't get packer to build from source (seems like AWS libraries may have changed, and perhaps other things), e.g.

```
# github.com/mitchellh/packer/builder/amazon/common
builder/amazon/common/artifact.go:75: cannot use regionConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_ami_region_copy.go:90: cannot use awsConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_create_tags.go:39: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
```

If I try to build this ansible provisioner anyway, I get this:

    # github.com/bhcleek/packer-provisioner-ansible/provisioner/ansible
    provisioner/ansible/provisioner.go:27: undefined: packer.ConfigTemplate

I'll keep digging at it.

**But**, in the meantime: this seems like a more complex solution to the problem than I was expecting, when I first thought about avoiding the existing "ansible local" I thought that the solution would involve extracting the remote machine's ip address and some key info and just letting Ansible hash it out.  What is the advantage to *this* approach (other than the fact that you've completed it?)

I'm looking forward to making it work and taking it for a spin.

**Comment by hartzell** [comment]
The broken build was fixed in #2890 (thanks!)

This no longer builds, Mitchell removed ConfigTemplate in commit 1d3a4d6aa2b2c969bb52f00e27113d21a28ad793.

I can take a whack at adapting the pull request, but I could use a bit of a push.  Why was it removed?  Was it replaced with something else?  It looks like the chef-* provisioners implement a ConfigTemplate of their own, should this provisioner do that too?

Thanks for any hints and/or clues.

**Comment by rickard-von-essen** [comment]
The config templet interpolation is now automatic except if you explicitly
exclude the config key.

**Comment by bhcleek** [comment]
I'm happy to make any changes to this PR in order to build against latest master, but I'm not sure what the preferred workflow is for packer. Should I merge master into my branch, or just rebase my branch onto master?

**Comment by rickard-von-essen** [comment]
Rebase

**Comment by bhcleek** [comment]
I rebased onto the latest master.

@hartzell to answer your earlier question, the advantage to this approach is that it allows Ansible to execute its tasks using SSH, while allowing the Packer abstraction of communication to function correctly. Although most Packer builders use SSH to communicate with the node, the SSH communication details are not exposed to provisioners. Packer has also added a WinRM communicator, and presumably there may be other kinds of communicators in the future.

**Comment by hartzell** [comment]
@bhcleek -- Thanks for the followup (and thanks^2 for the code)!

**Comment by Zeelot** [comment]
For people that stumble into here looking for this functionality, I thought I would point out that the `shell-local` provisioner should allow very similar functionality. I simply call `ansible-playbook` with it and treat it as if I was provisioning the machine myself without packer. In order to be able to provision just the machine packer launched (in my case, an ec2 instance), I created a `uuid` with packer  and set it as a `packer-id` tag on the ec2 instance. I can then pass `tag_packer-id_<uuid>` into the ansible playbook and only provision that machine.

After looking around for proper ansible support in packer, I think I actually prefer this method as it gives me direct control over the command being run without any hidden API. I run ansible commands all day and this just looks like any other ansible command. Hope it's useful to someone else!

**Comment by Zeelot** [comment]
The `uuid` thing isn't needed if there is a variable holding the launched instance's IP somewhere… but I couldn't find it. :( not sure if I just missed something.

**Comment by hartzell** [comment]
FWIW, here's a thumbs up report (Mac OS, building a CentOS 6.7 image).

@cbednarski  **I'd love to see this functionality in packer!**   What's standing between here and a merge?

I'm new to the Packer source tree and I stumbled about a bit.   For posterity's sake, here are some notes:

I cloned @bhcleek 's packer fork: https://github.com/bhcleek/packer into $GOPATH/src/github.com/mitchellh/packer

I ran 

```
make updatedeps
cd command
go generate
cd ..
make dev
```

and that resulted in a packer binary that included the *ansible* provisioner.

I set up the keys I need:

```
ssh-keygen -t rsa -f ./packer_host_private_key
ssh-keygen -t rsa -f ./my_key
cp my_key.pub authorized_keys
```

Finally I touched up the ansible bit of a CentOS-6.7.json (on CentOS 6.7 sftp-server isn't where @bhcleek expected it):

```json
{
    "type": "ansible",
    "playbook_file": "playbooks/playbook.yml",
    "extra_arguments": ["--private-key", "my_key", "-v", "-c", "ssh"],
    "ssh_authorized_key_file": "./authorized_keys",
    "ssh_host_key_file": "./packer_host_private_key",
    "sftp_command": "/usr/libexec/openssh/sftp-server -e"
},
```

and created an ansible.cfg file that contained:

```
[defaults]
host_key_checking = False
```

and ran packer.

```
packer build CentOS-6.7.json
```

Et, voila!

**Comment by dkhenry** [comment]
so I have made a few significant changes to this, and I hope they will be accepted as I feel they make this module easier to use.

1. I have changed the requirements to need both the ssh key files or neither of the files.
2. If you don't provide any key files, I will generate a key for you. 
3. I added the --private-key flag to the ansible invocation as I found it to be required
4. I updated the documentation to add in all those changes

To test it I had to build the binary directly ( navigate to the plugins directory and run go build, then copy the binary to my $PATH ). So I am not sure what really needs to be done to make it build by default.

The code is here https://github.com/dkhenry/packer/commit/124f650f4fcaf262c2358e536cad57ed63319640 

Not quite sure how I could add it to this merge request.

**Comment by LinusU** [comment]
@dkhenry that sounds awesome!

If you push the commit to your `ansible-provisioner`, it will automatically show up in this pull request.

Also, is there any scenario where you want to provide your own keys? I'm not seeing the use for that at all, maybe I'm missing something, or maybe it's better to just take it out

**Comment by bhcleek** [comment]
@dkhenry I appreciate the effort to make this PR better.

I'm not comfortable using the same private key for both the user and the server; I'd rather stick with security best practices here. However, a user could certainly *choose* to use her private key as the host key. At the risk of explaining something you already understand: SSH servers have a key that uniquely identifies the server. This allows one to verify that the host is the expected host (have you ever received a "host key verification failed" error when connecting to a server whose keys have been rotated since you last connected?).

I understand the desire to generate a host key, though, and would welcome a change that generates and uses one, but I'd prefer to disentangle the generation of a host key from `ssh_authorized_key_file`. If you automatically generate the host key, you'll also need to invoke Ansible with host key checking disabled. I'm not sure that's a good idea, though I could be persuaded.

`--private-key` is not required for the `ansible-playbook` invocation. The user may have the private key loaded into their SSH agent. The user may be using her default key. The user may have an SSH config that specifies which key to use. By adding `--private-key`, you'll be precluding other private key sources from being used. If a user wants to specify `--private-key`, the `extra_arguments` option is available.

**Comment by richardzone** [comment]
+1 to this. The current approach of running ansible-local inside just doesn't make sense

**Comment by dkhenry** [comment]
@bhcleek so I am totally confused as to where each of these keys are used then in the process. After reading the code I thought that the authorized_key_file ( which is only used to fetch a public key ) is what is used to accept the private key from the host machine via Ansible. I don't know why but I have it in my mind that the process looks like this

Provision Starts
Start up an ssh server on the host machine listening on `port`. This server validates connections from people using the `authorized_key_file`
The SSH Server adds in its host key so others know who it is ( `host_key_file`)
The system starts up Ansible, Ansible is configured to talk to the SSH server we just started using a private key that matches up with `authorized_key_file`, Additionally there needs to be an entry in the Users ~/.ssh/known_hosts file that correlates with `host_key_file` and an SSH server running on localhost
The Ansible commands are then relayed across the Packer Communicator to get invoked on the remote machine ( this is done over the standard packer ssh channel ) 

If this is the case then may I propose to leave the generalized case of autogenerating everything ( both keys, adding arguments to ansible, and turning off host_key_checking) so if a user wants everything just works, but if you specify key's to use then don't make any changes and rely on the users environmental set up to validate trust.

**Comment by bhcleek** [comment]
Your understanding isn't that far off. In fact, all of your bullet points are basically right. But the way I read your key generation, the same private key will be used for both the user and the server, which I don't want to do for the same reasons that you wouldn't create a server whose host key was the private key that you use to connect.

As I said, I understand the desire to auto generate a host key, but I think that should be decoupled from whether or not the user has specified the `ssh_authorized_key_file`.

I could get on board with auto-generating the private key, too, and only adding `--private-key` to the `ansible-playbook` invocation if the private key was auto-generated. Of course, auto-generate the private key should occur only if the user `ssh_authorized_key_file` is unset, and the value of `ssh_host_key_file` shouldn't be a factor in whether or not the user's private key is auto-generated.

I'd really like to get the Packer maintainers to give some feedback before we start making changes, though. There are other changes that I'd like to make that I've held off on, because I don't want to generate too much commit activity until we have some feedback. If this PR ever gets any traction with the maintainers, then I'd like to consider using a dynamic port in place of the `local_port` setting.

**Comment by dkhenry** [comment]
Ok I think I see what your getting at. I am currently using the module with great success to automate parts of my delivery pipeline so I am going to keep plugging away in my fork, but I would be happy to implement anything @cbednarski  would suggest in getting this merged upstream.

**Comment by habnabit** [comment]
I've made a few changes to @bhcleek's branch: https://github.com/bhcleek/packer/compare/ansible-provisioner-more-error...habnabit:ansible-provisioner-more-error

Importantly:
 - I solved a panic I was getting whenever the plugin exited because it was trying to send to a closed channel.
 - I added `ssh_skip_request_pty` to the AWS builders, which needed to be set to `true` to get this provisioner to provision an AMI. Tested with the latest-at-the-time ansible 2.0 (can't find the commit) and ubuntu 14.04 on EC2.

**Comment by habnabit** [comment]
Oh, it seems the latter part of this is superseded by #1968, which apparently wasn't merged into the bit I branched from.

**Comment by habnabit** [comment]
Rebased onto 71d8c6610ab5cc0026d4cdb2a42d97acf8b6d17e.

**Comment by bhcleek** [comment]
@habnabit, I'd be happy to consider incorporating your changes, especially if you're seeing a panic. The branch, though should be `bhcleek:ansible-provisioner`. In the meantime, I'll create a unit test to verify the solution.

However, while it is true the `Ui.Error()` *may* be safe for concurrent use, but it's not clearly spelled out in the interface, and so shouldn't be assumed. Can anyone on the packer team confirm that `Ui.Error()` is always safe for concurrent use?

**Comment by habnabit** [comment]
@bhcleek, that was something I wasn't sure about, but:

1. It's already being used from at least two different goroutines (line 59 doesn't use `errc`: `c.ui.Error(fmt.Sprintf("listen.Accept failed: %v", err))`).
2. AFAICT, `ui.Error` just sends an RPC message.

**Comment by habnabit** [comment]
@bhcleek, anyway, updated: https://github.com/bhcleek/packer/compare/ansible-provisioner...habnabit:ansible-provisioner

**Comment by bhcleek** [comment]
I resolved the possible panic. But you're right, there are some possible race conditions in the code. Pragmatically, it may not be much of an issue, but since the `Ui` interface has no concurrency guarantees, I don't believe the plugin should assume the RPC client doesn't do something that's not safe for concurrency. I'll work to resolve those race conditions and add some tests in the next few days.

**Comment by wizwjw** [comment]
+1 
Really looking forward this!

**Comment by jk563** [comment]
Great addition, hope it gets in soon, been fantastic for my work flow.

**Comment by ptolemy428** [comment]
+1
Would love to see this being merged/released. We're heavily relying on Ansible and would love to use Packer + Ansible (with remote provisioning)!

**Comment by bhcleek** [comment]
@ptolemy, you can use bhcleek/packer-provisioner-ansible until this is merged.

**Comment by mmoya** [comment]
+1

**Comment by ahelal** [comment]
Amazing work hope its merged soon

**Comment by cbednarski** [comment]
@bhcleek Thanks for the hard work on this feature! We'll be shipping this with 0.9. :tada: :balloon:

**Comment by bhcleek** [comment]
That's great news! :100:

**Comment by ptolemy428** [comment]
It's really great to see this feature being merged! @bhcleek @cbednarski 
There are differences and issues (that can not be ignored) between running ansible locally and remotely. This is even more true when you work with a large existing Ansible repo (to reuse provisioning logic) where there are shared var files, re-used roles, encrypted data in ansible vault, etc. 
I was at the verge of moving away from Packer this morning as I found myself having to do "too many workarounds" to get Packer and Ansible working together using the 'local provisioner". 
This is a great step forward. I hope in the release 0.9, we can provide a smooth experience to be able to run ansible locally on the provisioning machine, in this case we only need to set up all dependencies (required for provisioning logics, i.e. pip, boto) in one place (say CI server) and provision the remote box over ssh.

**Comment by cbednarski** [comment]
@ptolemy428 Definitely! Kudos to @bhcleek for making the magic happen. If you have any issues or feedback going forward please feel free to open a new issue or pull-request! Thanks!

**Comment by mtb-xt** [comment]
Packer generates its own ssh keys anyway, why those keys are not reused for ansible connection?

**Comment by poshest** [comment]
I know it's happened already, but +1 and thanks to @bhcleek. Really looking forward to 0.9 now.

**Comment by leopepe** [comment]
+1 indeed. I've been following this issue a long time :P
Thanks @bhcleek
