### ISSUE TITLE
The build seems to be broken.

### ISSUE THREAD

**Issue by hartzell** [mitchellh/packer#2890]
I'm working on a mac (OSX 10.10.5) with go via homebrew (version go1.5.1 darwin/amd64).

This is my first attempt to build packer and/but I can't get packer to build correctly.  On the branches tab of the Githubpage, the "default" branch is marked with a red X, clicking through leads to a similar failure to what I'm seeing.  

I ran `make updatedeps` with no errors, but `make` reports:

```
georgewh-L0DKQ1:packer georgewh$ make
go get -v -d ./...
go test ./...  -timeout=15s | tee packer-test.log
# github.com/mitchellh/packer/builder/amazon/common
builder/amazon/common/artifact.go:75: cannot use regionConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_ami_region_copy.go:90: cannot use awsConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_create_tags.go:39: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_modify_ami_attributes.go:93: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
# github.com/mitchellh/packer/builder/amazon/common
builder/amazon/common/artifact.go:75: cannot use regionConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_ami_region_copy.go:90: cannot use awsConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_create_tags.go:39: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_modify_ami_attributes.go:93: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
FAIL	github.com/mitchellh/packer [build failed]
FAIL	github.com/mitchellh/packer/builder/amazon/chroot [build failed]
FAIL	github.com/mitchellh/packer/builder/amazon/common [build failed]
[...]
1 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # github.com/mitchellh/packer/builder/amazon/common
builder/amazon/common/artifact.go:75: cannot use regionConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_ami_region_copy.go:90: cannot use awsConfig (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_create_tags.go:39: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
builder/amazon/common/step_modify_ami_attributes.go:93: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
	*aws.Config does not implement client.ConfigProvider (missing ClientConfig method)

==> Copying binaries for this platform...
find: ./pkg/darwin_amd64: No such file or directory

==> Results:
```

**Comment by cbednarski** [comment]
@hartzell Thanks for the report. I think the AWS upstream has broken backwards compatibility somehow. I'll take a look.

**Comment by rubbish** [comment]
We saw this as well in one of our automated builds and I was surprised that `make dev` didn't exit with a non-zero when this happened.

**Comment by rubbish** [comment]
https://github.com/aws/aws-sdk-go/commit/1a69d069352edadd48f12b0f2c5f375de4a636d7 looks to be the breaking commit. Terraform fixed it via https://github.com/hashicorp/terraform/commit/cadbbbae0885218b7c14b7169c8bbe4d3ec4d2d8

**Comment by rubbish** [comment]
@cbednarski I PR'd a fix in #2891

**Comment by hartzell** [comment]
**Thanks** for the quick response!
